### ISSUE TITLE
Agendamento de palestras

### ISSUE THREAD

**Issue by MaiconMares** [MaiconMares/web_coding_challenge#1]
**Describe the solution you'd like**
Por meio de um `endpoint` receber arquivo com as palestras e seus respectivos tempos de duração. Realizar o agendamento das palestras dentro das restrições de tempo. Alocar o máximo de palestras possível dentro de cada janela de tempo (sessão) de modo que o tempo de cada uma seja melhor aproveitado.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/MaiconMares/web_coding_challenge/assets/47460478/8827d641-6e24-422c-b589-227480906d25)

**Tasks**
- [x] Modelagem do banco de dados
- [x] Implementar entidades
- [x] Implementar `endpoint`
- [x] Implementar algoritmo de `scheduling`
- [x] Testes (unidade e integração)
